name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4.7.1
      with:
        python-version: 3.8 # tai muu haluamasi versio

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Lis채채 t채h채n muita vaiheita, kuten linttaus tai muu koodin tarkistus

    - name: Run tests
      run: |
        pip install pytest
        pytest

    # TestSpace.com asennus ja tulosten julkaisu
    - uses: testspace-com/setup-testspace@v1
      with:
        domain: ${{github.repository_owner}}

    - name: Publish Results to Testspace
      run: testspace [${{ matrix.os}}]./testcontent/*.xml

